UtmCounselingSystem/Controllers/ApplyAppointmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace UtmCounselingSystem.Controllers
{
    public class ApplyAppointmentController : Controller
    {
        // GET:  ApplyAppointment
        public ActionResult Index()
        {
            return View();
        }

        // GET:  ApplyAppointment/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET:  ApplyAppointment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST:  ApplyAppointment/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET:  ApplyAppointment/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST:  ApplyAppointment/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET:  ApplyAppointment/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST:  ApplyAppointment/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

UtmCounselingSystem/Controllers/AppointmentTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UtmCounselingSystem.Constants;
using UtmCounselingSystem.Contracts;
using UtmCounselingSystem.Data;
using UtmCounselingSystem.Models;

namespace UtmCounselingSystem.Controllers
{
    [Authorize(Roles = Roles.Administrator)]
    public class AppointmentTypesController : Controller
    {
        private readonly IAppointmentTypeRepository appointmentTypeRepository;
        private readonly IMapper mapper;
        private readonly IAppointmentAllocationRepository appointmentAllocationRepository;

        public AppointmentTypesController(IAppointmentTypeRepository appointmentTypeRepository
            , IMapper mapper
            ,IAppointmentAllocationRepository appointmentAllocationRepository)
        {
            this.appointmentTypeRepository = appointmentTypeRepository;
            this.mapper = mapper;
            this.appointmentAllocationRepository = appointmentAllocationRepository;
        }

        // GET: AppointmentTypes
        public async Task<IActionResult> Index()
        {
            var appointmentTypes = mapper.Map<List<AppointmentTypeVM>>(await appointmentTypeRepository.GetAllAsync());
            return View(appointmentTypes);
        }

        // GET: AppointmentTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var appointmentType = await appointmentTypeRepository.GetAsync(id);
            if (appointmentType == null)
            {
                return NotFound();
            }

            var appointmentTypeVM = mapper.Map<AppointmentTypeVM>(appointmentType);
            return View(appointmentTypeVM);
        }

        // GET: AppointmentTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AppointmentTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AppointmentTypeVM appointmentTypeVM)
        {
            if (ModelState.IsValid)
            {
                var appointmentType = mapper.Map<AppointmentType>(appointmentTypeVM);
                await appointmentTypeRepository.AddAsync(appointmentType);
                return RedirectToAction(nameof(Index));
            }
            return View(appointmentTypeVM);
        }

        // GET: AppointmentTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var appointmentType = await appointmentTypeRepository.GetAsync(id);
            if (appointmentType == null)
            {
                return NotFound();
            }
            var appointmentTypeVM = mapper.Map<AppointmentTypeVM>(appointmentType);
            return View(appointmentTypeVM);
        }

        // POST: AppointmentTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, AppointmentTypeVM appointmentTypeVM)
        {
            if (id != appointmentTypeVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var appointmentType = mapper.Map<AppointmentType>(appointmentTypeVM);
                    await appointmentTypeRepository.UpdateAsync(appointmentType);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await appointmentTypeRepository.Exists(appointmentTypeVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appointmentTypeVM);
        }

        // POST: LeaveTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await appointmentTypeRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> AllocateAppointment(int id)
        //{
        //    await appointmentAllocationRepository.AppointmentAllocation(id);
        //    return RedirectToAction(nameof(Index));
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AllocateAppointment(int id)
        {
            await appointmentAllocationRepository.AppointmentAllocaton(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

UtmCounselingSystem/Controllers/ClientsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using UtmCounselingSystem.Constants;
using UtmCounselingSystem.Data;
using UtmCounselingSystem.Models;

namespace UtmCounselingSystem.Controllers
{
    public class ClientsController : Controller
    {
        private readonly UserManager<Client> userManager;
        private readonly IMapper mapper;

        public ClientsController(UserManager<Client> userManager, IMapper mapper)
        {
            this.userManager = userManager;
            this.mapper = mapper;
        }
        // GET: ClientsController
        public async Task<IActionResult> IndexAsync()
        {
            var clients = await userManager.GetUsersInRoleAsync(Roles.User);
            var model = mapper.Map<List<ClientListVM>>(clients);
            return View(model);
        }

        // GET: ClientsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClientsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClientsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClientsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ClientsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClientsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ClientsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(IndexAsync));
            }
            catch
            {
                return View();
            }
        }
    }
}

UtmCounselingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UtmCounselingSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UtmCounselingSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UTM Counseling System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApplyAppointment" asp-action="Create">Apply Appointment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="">My Appointment</a>
                        </li>
                        @if (User.IsInRole("Administrator"))
                        {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                                </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Appointment Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-controller="AppointmentTypes" asp-action="Index">Appointment Types</a></li>
                                    <li><a class="dropdown-item" href="#">Appointment Allocations</a></li>
                                    <li><a class="dropdown-item" href="#">Appointment Requests</a></li>
                                    <li><a class="dropdown-item" href="#">Client Management</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UTM Counseling System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>